FROM ubuntu:18.04

ARG SALTVERSION=3001

RUN \
  apt-get update && \
  apt-get install -y wget gnupg && \
  wget -O - https://repo.saltstack.com/py3/ubuntu/18.04/amd64/${SALTVERSION}/salt-archive-keyring.gpg | apt-key add - && \
  echo "deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/${SALTVERSION} bionic main" | tee /etc/apt/sources.list.d/saltstack.list && \
  apt-get update && \
  apt-get install -y salt-common
